### ISSUE TITLE
react-native-on-web bundle

### ISSUE THREAD

**Issue by bengele** [Beven91/react-native-on-web#2]
老板，
ERROR in chunk node_modules/component-classes/index [entry]
../../[name].js
Cannot read property 'resource' of null

ReactNativeOnWeb Bundle error.....

打包最后报此错。有点懵逼。

**Comment by Beven91** [comment]
谢谢你的反馈，非常抱歉回复的晚了，请问是否有使用代码拆分配置？

**Comment by bengele** [comment]
谢谢老板，经查是我的代码的问题引发的。已经解决了，有个新的问题，我的图片资源的目录是自己配置的，打包web时，是不是需要在.packager.js中配置图片的路径？

**Comment by Beven91** [comment]
是指图片资源存放的物理位置吗？
可以在`.packager.js` 中配置下`imageAssets` 例如:
```js
{
  imageAssets:[
     path.resolve('../images'),//假设在web目录上级目录有个images目录 
 ]
}
```

然后你可以如此引用对应的图片

```jsx
   <Image src={require('image!a.png')} />
```

**Comment by bengele** [comment]
Ok 我试试
