### ISSUE TITLE
使用react-navigation做导航出现的错误。

### ISSUE THREAD

**Issue by bengele** [Beven91/react-native-on-web#3]
ERROR  /Users/ben/Documents/work/ntt/client/web/ntt-react-native-web/web/node_modules/react-navigation/src/navigators/createNavigator.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                          
无法引用React

**Comment by bengele** [comment]
/**
   * 开发环境是否node_modules下所有文件都使用babel编译
   * 如果设置成true  则无需设置es6Modules 但是会导致开发环境启动速度变慢
   * 如果设置成false 当你的项目的依赖模块是es6的代码 
   * 可以在es6Modules 下设置白名单
   */
  compileAll: false,

设置了为false，看注释是表示以来es6

**Comment by Beven91** [comment]
是的，默认设置为false ，你需要吧 `react-navigation` 添加到 es6Modules配置里边，如下:
```js
 compileAll:false,
 es6Modules: [
   /react-navigation/  
 ]
```

**Comment by bengele** [comment]
问题都解决了，在rnw-bundler模块下的 babelRC.js中，
function includes(js) {
  js = js.split('node_modules').pop();
  for (var i = 0, k = MODULES_REG.length; i < k; i++) {
    if (js.indexOf('react-native-on-web') < 0 && MODULES_REG[i].test(js)) {
      return true;
    }
  }
}

js.indexOf('react-native-on-web') < 0 这句话会导致 es6Modules列表无效

**Comment by Beven91** [comment]
是的，在后面有个升级到webpack4的版本附带解决了这个问题，目前在alpha版本。

**Comment by Beven91** [comment]
你莫非是使用当前库在运行项目？

**Comment by bengele** [comment]
@Beven91 打出来到bundle，pm2 本机启动报错哦。
Error: Cannot find module 'react-native-on-web/provider'

**Comment by Beven91** [comment]
请问你使用的版本是多少的？react-native-on-web

**Comment by bengele** [comment]
react-native-on-web -V
5.0.4

**Comment by Beven91** [comment]
那个文件被删除了，后面我加下

**Comment by bengele** [comment]
兄弟，可不可以加个qq请教下web端的一些问题？

**Comment by Beven91** [comment]
504007422

**Comment by Beven91** [comment]
好的呀，这是我的QQ :504007422

**Comment by bengele** [comment]
@Beven91 验证信息需要真实姓名

**Comment by Beven91** [comment]
周碧文

**Comment by Beven91** [comment]
在版本 5.1.0中以解决这个问题
